; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:cvc_f405rg]
platform = ststm32
board = cvc_f405rg

board_build.ldscript = STM32F405RGTX_FLASH.ld

lib_deps = STM32F4xx_HAL_Driver, CMSIS, FreeRTOS

build_flags =
  -mfpu=fpv5-sp-d16
  -mfloat-abi=softfp
  -I lib/STM32F4xx_HAL_Driver/Inc
  -I lib/STM32F4xx_HAL_Driver/Inc/Legacy
  -L lib/STM32F4xx_HAL_Driver/Src
  -I include/core
  -I include/cvc
  -I include
  -I lib/CMSIS/Device/ST/STM32F4xx/Include
  -I lib/CMSIS/Include
  -I lib/FreeRTOS/Source/include
  -I lib/FreeRTOS/Source/CMSIS_RTOS_V2
  -I lib/FreeRTOS/Source/portable/GCC/ARM_CM4F
  -I lib/FreeRTOS/Source/portable/MemMang

build_type = debug
lib_archive = no

debug_tool = stlink
debug_speed = 4000
debug_extra_cmds =
  monitor gdb_breakpoint_override hard
  set breakpoint always-inserted on
  set remote hardware-breakpoint-limit 6
  set remote hardware-watchpoint-limit 4