/*
 * tasks.h
 *
 * Created on 6/7/2025
 * Andrei Gerashchenko
 */

#ifndef CVC_TASKS_H
#define CVC_TASKS_H

#include <cmsis_os2.h>

#define STATEMACHINE_TASK_NAME "stateMachineTask"
#define STATEMACHINE_TASK_STACK_SIZE 128
#define STATEMACHINE_TASK_PRIORITY osPriorityNormal
#define STATEMACHINE_TASK_INTERVAL 1

#define THROTTLE_TASK_NAME "throttleTask"
#define THROTTLE_TASK_STACK_SIZE 128
#define THROTTLE_TASK_PRIORITY osPriorityAboveNormal
#define THROTTLE_TASK_INTERVAL 1

#define CAN_RX_TASK_NAME "canRxTask"
#define CAN_RX_TASK_STACK_SIZE 128
#define CAN_RX_TASK_PRIORITY osPriorityHigh
#define CAN_RX_TASK_INTERVAL 1

#define CAN_1_TX_TASK_NAME "can1TxTask"
#define CAN_1_TX_TASK_STACK_SIZE 128
#define CAN_1_TX_TASK_PRIORITY osPriorityNormal
#define CAN_1_TX_TASK_INTERVAL 1

#define CAN_2_TX_TASK_NAME "can2TxTask"
#define CAN_2_TX_TASK_STACK_SIZE 128
#define CAN_2_TX_TASK_PRIORITY osPriorityNormal
#define CAN_2_TX_TASK_INTERVAL 1

#define TORQUE_CALCULATE_TASK_NAME "torqueTask"
#define TORQUE_CALCULATE_TASK_STACK_SIZE 128
#define TORQUE_CALCULATE_TASK_PRIORITY osPriorityAboveNormal
#define TORQUE_CALCULATE_TASK_INTERVAL 3

#define TORQUE_COMMAND_TASK_NAME "torqueCommandTask"
#define TORQUE_COMMAND_TASK_STACK_SIZE 128
#define TORQUE_COMMAND_TASK_PRIORITY osPriorityNormal
#define TORQUE_COMMAND_TASK_INTERVAL 3

#define TORQUE_LIMIT_TASK_NAME "torqueLimitTask"
#define TORQUE_LIMIT_TASK_STACK_SIZE 128
#define TORQUE_LIMIT_TASK_PRIORITY osPriorityNormal
#define TORQUE_LIMIT_TASK_INTERVAL 10

#define STATEMACHINE_OUTPUT_TASK_NAME "stateMachineOutputTask"
#define STATEMACHINE_OUTPUT_TASK_STACK_SIZE 128
#define STATEMACHINE_OUTPUT_TASK_PRIORITY osPriorityBelowNormal
#define STATEMACHINE_OUTPUT_TASK_INTERVAL 10

#define BRAKE_LIGHT_TASK_NAME "brakeLightTask"
#define BRAKE_LIGHT_TASK_STACK_SIZE 128
#define BRAKE_LIGHT_TASK_PRIORITY osPriorityLow
#define BRAKE_LIGHT_TASK_INTERVAL 1

#define DASHBOARD_BROADCAST_TASK_NAME "dashboardBroadcastTask"
#define DASHBOARD_BROADCAST_TASK_STACK_SIZE 128
#define DASHBOARD_BROADCAST_TASK_PRIORITY osPriorityLow
#define DASHBOARD_BROADCAST_TASK_INTERVAL 10

#define WHEEL_SPEEDS_TASK_NAME "wheelSpeedsTask"
#define WHEEL_SPEEDS_TASK_STACK_SIZE 128
#define WHEEL_SPEEDS_TASK_PRIORITY osPriorityLow
#define WHEEL_SPEEDS_TASK_INTERVAL 10

#define ANALOG_READ_TASK_NAME "analogReadTask"
#define ANALOG_READ_TASK_STACK_SIZE 128
#define ANALOG_READ_TASK_PRIORITY osPriorityBelowNormal
#define ANALOG_READ_TASK_INTERVAL 1


#endif  // CVC_TASKS_H